import { UNKNOWN_TYPES } from './constants';
import { ValueType } from './ParsedValueTypes';
import type { Module, ValueOf } from './WoWInterfaceAST';

export type Entries<T> = {
  [K in keyof T]-?: [K, T[K]];
}[keyof T][];

export const entriesOf = <T extends object>(obj: T) =>
  Object.entries(obj) as Entries<T>;

export type Values<T> = T[keyof T][];

export const valuesOf = <T extends object>(obj: T) =>
  Object.values(obj) as Values<T>;

export const loadParsedModules = async () => {
  const modules: Module[] = await Bun.file(
    './APIDocumentationGenerated.json',
  ).json();
  return modules;
};

export function assertNever(value?: never): never {
  throw new Error(
    `ERROR! Reached forbidden guard function with unexpected value: ${JSON.stringify(value)}`,
  );
}

export function assert(condition: boolean, message: string): asserts condition {
  if (!condition) {
    throw new Error(message);
  }
}

export function normalizeType(type: string): string {
  if (UNKNOWN_TYPES[type]) {
    return UNKNOWN_TYPES[type];
  }
  switch (type) {
    case ValueType.undefined:
      return 'nil';
    case ValueType.System:
      return '';
    case ValueType.Function:
      return '';
    case ValueType.WOWGUID:
      return 'string';
    case ValueType.number:
      return 'number';
    case ValueType.bool:
      return 'boolean';
    case ValueType.table:
      return 'table';
    case ValueType.AccountStoreCategoryInfo:
      return 'AccountStoreCategoryInfo';
    case ValueType.AccountStoreCurrencyInfo:
      return 'AccountStoreCurrencyInfo';
    case ValueType.AccountStoreItemInfo:
      return 'AccountStoreItemInfo';
    case ValueType.AccountStoreState:
      return 'AccountStoreState';
    case ValueType.Event:
      return 'Event';
    case ValueType.Structure:
      return 'Structure';
    case ValueType.cstring:
      return 'cstring';
    case ValueType.AccountStoreCategoryType:
      return 'AccountStoreCategoryType';
    case ValueType.fileID:
      return 'fileID';
    case ValueType.AccountStoreItemStatus:
      return 'AccountStoreItemStatus';
    case ValueType.AccountStoreItemFlag:
      return 'AccountStoreItemFlag';
    case ValueType.time_t:
      return 'time_t';
    case ValueType.SimpleTexture:
      return 'SimpleTexture';
    case ValueType.luaIndex:
      return 'luaIndex';
    case ValueType.AddOnPerformanceMessage:
      return 'AddOnPerformanceMessage';
    case ValueType.AddOnProfilerMetric:
      return 'AddOnProfilerMetric';
    case ValueType.AddOnPerformanceMessageType:
      return 'AddOnPerformanceMessageType';
    case ValueType.string:
      return 'string';
    case ValueType.uiAddon:
      return 'uiAddon';
    case ValueType.AddOnEnableState:
      return 'AddOnEnableState';
    case ValueType.Enumeration:
      return 'Enumeration';
    case ValueType.textureKit:
      return 'textureKit';
    case ValueType.AreaPOIInfo:
      return 'AreaPOIInfo';
    case ValueType.vector2:
      return 'vector2';
    case ValueType.ItemLocation:
      return 'ItemLocation';
    case ValueType.BigUInteger:
      return 'BigUInteger';
    case ValueType.AuctionInfo:
      return 'AuctionInfo';
    case ValueType.BidInfo:
      return 'BidInfo';
    case ValueType.ItemKey:
      return 'ItemKey';
    case ValueType.CommoditySearchResultInfo:
      return 'CommoditySearchResultInfo';
    case ValueType.ItemCommodityStatus:
      return 'ItemCommodityStatus';
    case ValueType.ItemKeyInfo:
      return 'ItemKeyInfo';
    case ValueType.ItemSearchResultInfo:
      return 'ItemSearchResultInfo';
    case ValueType.OwnedAuctionInfo:
      return 'OwnedAuctionInfo';
    case ValueType.AuctionHouseTimeLeftBand:
      return 'AuctionHouseTimeLeftBand';
    case ValueType.AuctionHouseBrowseQuery:
      return 'AuctionHouseBrowseQuery';
    case ValueType.AuctionHouseError:
      return 'AuctionHouseError';
    case ValueType.AuctionHouseNotification:
      return 'AuctionHouseNotification';
    case ValueType.AuctionHouseFilterCategory:
      return 'AuctionHouseFilterCategory';
    case ValueType.AuctionStatus:
      return 'AuctionStatus';
    case ValueType.InventoryType:
      return 'InventoryType';
    case ValueType.AuctionHouseSortOrder:
      return 'AuctionHouseSortOrder';
    case ValueType.WOWMONEY:
      return 'WOWMONEY';
    case ValueType.ItemQuality:
      return 'ItemQuality';
    case ValueType.AzeriteEmpoweredItemLocation:
      return 'AzeriteEmpoweredItemLocation';
    case ValueType.ItemInfo:
      return 'ItemInfo';
    case ValueType.AzeriteEmpoweredItemPowerInfo:
      return 'AzeriteEmpoweredItemPowerInfo';
    case ValueType.AzeritePowerLevel:
      return 'AzeritePowerLevel';
    case ValueType.AzeriteEmpoweredItemPowerText:
      return 'AzeriteEmpoweredItemPowerText';
    case ValueType.AzeriteEssenceInfo:
      return 'AzeriteEssenceInfo';
    case ValueType.AzeriteMilestoneInfo:
      return 'AzeriteMilestoneInfo';
    case ValueType.AzeriteEssenceSlot:
      return 'AzeriteEssenceSlot';
    case ValueType.AzeriteItemLocation:
      return 'AzeriteItemLocation';
    case ValueType.BagIndex:
      return 'BagIndex';
    case ValueType.BankType:
      return 'BankType';
    case ValueType.BagSlotFlags:
      return 'BagSlotFlags';
    case ValueType.PlayerInfoCharacterData:
      return 'PlayerInfoCharacterData';
    case ValueType.ChrModelFeatureFlags:
      return 'ChrModelFeatureFlags';
    case ValueType.UnitSex:
      return 'UnitSex';
    case ValueType.BNetAccountInfo:
      return 'BNetAccountInfo';
    case ValueType.BNetGameAccountInfo:
      return 'BNetGameAccountInfo';
    case ValueType.RafLinkType:
      return 'RafLinkType';
    case ValueType.NotificationDbId:
      return 'NotificationDbId';
    case ValueType.CalendarEventIndexInfo:
      return 'CalendarEventIndexInfo';
    case ValueType.ClubId:
      return 'ClubId';
    case ValueType.CalendarEventInviteInfo:
      return 'CalendarEventInviteInfo';
    case ValueType.CalendarTime:
      return 'CalendarTime';
    case ValueType.CalendarEventType:
      return 'CalendarEventType';
    case ValueType.CalendarStatus:
      return 'CalendarStatus';
    case ValueType.CalendarDayEvent:
      return 'CalendarDayEvent';
    case ValueType.CalendarGuildFilterInfo:
      return 'CalendarGuildFilterInfo';
    case ValueType.CalendarEventID:
      return 'CalendarEventID';
    case ValueType.CalendarEventInfo:
      return 'CalendarEventInfo';
    case ValueType.CalendarGuildEventInfo:
      return 'CalendarGuildEventInfo';
    case ValueType.CalendarHolidayInfo:
      return 'CalendarHolidayInfo';
    case ValueType.CalendarMonthInfo:
      return 'CalendarMonthInfo';
    case ValueType.CalendarRaidInfo:
      return 'CalendarRaidInfo';
    case ValueType.CalendarInviteType:
      return 'CalendarInviteType';
    case ValueType.CalendarEventRepeatOptions:
      return 'CalendarEventRepeatOptions';
    case ValueType.ChatChannelInfo:
      return 'ChatChannelInfo';
    case ValueType.ChatChannelRuleset:
      return 'ChatChannelRuleset';
    case ValueType.colorRGB:
      return 'colorRGB';
    case ValueType.ChatChannelType:
      return 'ChatChannelType';
    case ValueType.RegisterAddonMessagePrefixResult:
      return 'RegisterAddonMessagePrefixResult';
    case ValueType.SendAddonMessageResult:
      return 'SendAddonMessageResult';
    case ValueType.ChatWhisperTargetStatus:
      return 'ChatWhisperTargetStatus';
    case ValueType.CinematicType:
      return 'CinematicType';
    case ValueType.CameraModeAspectRatio:
      return 'CameraModeAspectRatio';
    case ValueType.ClientSceneType:
      return 'ClientSceneType';
    case ValueType.ClubStreamId:
      return 'ClubStreamId';
    case ValueType.ClubRoleIdentifier:
      return 'ClubRoleIdentifier';
    case ValueType.ClubType:
      return 'ClubType';
    case ValueType.ClubMessageIdentifier:
      return 'ClubMessageIdentifier';
    case ValueType.ClubInfo:
      return 'ClubInfo';
    case ValueType.ClubLimits:
      return 'ClubLimits';
    case ValueType.ClubPrivilegeInfo:
      return 'ClubPrivilegeInfo';
    case ValueType.ValidateNameResult:
      return 'ValidateNameResult';
    case ValueType.ClubMessageInfo:
      return 'ClubMessageInfo';
    case ValueType.ClubSelfInvitationInfo:
      return 'ClubSelfInvitationInfo';
    case ValueType.ClubErrorType:
      return 'ClubErrorType';
    case ValueType.ClubMemberInfo:
      return 'ClubMemberInfo';
    case ValueType.ClubStreamInfo:
      return 'ClubStreamInfo';
    case ValueType.ClubRestrictionReason:
      return 'ClubRestrictionReason';
    case ValueType.ClubFieldType:
      return 'ClubFieldType';
    case ValueType.ClubActionType:
      return 'ClubActionType';
    case ValueType.ClubInvitationId:
      return 'ClubInvitationId';
    case ValueType.ClubMemberPresence:
      return 'ClubMemberPresence';
    case ValueType.ClubMessageRange:
      return 'ClubMessageRange';
    case ValueType.ClubRemovedReason:
      return 'ClubRemovedReason';
    case ValueType.ClubTicketInfo:
      return 'ClubTicketInfo';
    case ValueType.ClubInvitationCandidateStatus:
      return 'ClubInvitationCandidateStatus';
    case ValueType.ClubStreamNotificationFilter:
      return 'ClubStreamNotificationFilter';
    case ValueType.ClubStreamType:
      return 'ClubStreamType';
    case ValueType.PvPFaction:
      return 'PvPFaction';
    case ValueType.kstringClubMessage:
      return 'kstringClubMessage';
    case ValueType.ClubFinderDisableReason:
      return 'ClubFinderDisableReason';
    case ValueType.ClubSettingsInfo:
      return 'ClubSettingsInfo';
    case ValueType.ClubFinderRequestType:
      return 'ClubFinderRequestType';
    case ValueType.PlayerClubRequestStatus:
      return 'PlayerClubRequestStatus';
    case ValueType.RecruitingClubInfo:
      return 'RecruitingClubInfo';
    case ValueType.ClubFinderApplicationUpdateType:
      return 'ClubFinderApplicationUpdateType';
    case ValueType.ClubFinderClubPostingStatusFlags:
      return 'ClubFinderClubPostingStatusFlags';
    case ValueType.ClubFinderPostingReportType:
      return 'ClubFinderPostingReportType';
    case ValueType.ClubFinderSettingFlags:
      return 'ClubFinderSettingFlags';
    case ValueType.BigInteger:
      return 'BigInteger';
    case ValueType.GuildTabardInfo:
      return 'GuildTabardInfo';
    case ValueType.ConfigurationWarning:
      return 'ConfigurationWarning';
    case ValueType.ConnectionIptype:
      return 'ConnectionIptype';
    case ValueType.stringView:
      return 'stringView';
    case ValueType.ConsoleColorType:
      return 'ConsoleColorType';
    case ValueType.ConsoleCategory:
      return 'ConsoleCategory';
    case ValueType.ConsoleCommandType:
      return 'ConsoleCommandType';
    case ValueType.ConsoleScriptCollectionData:
      return 'ConsoleScriptCollectionData';
    case ValueType.ConsoleScriptData:
      return 'ConsoleScriptData';
    case ValueType.ContainerItemInfo:
      return 'ContainerItemInfo';
    case ValueType.ItemPurchaseCurrency:
      return 'ItemPurchaseCurrency';
    case ValueType.ItemPurchaseInfo:
      return 'ItemPurchaseInfo';
    case ValueType.ItemPurchaseItem:
      return 'ItemPurchaseItem';
    case ValueType.ItemQuestInfo:
      return 'ItemQuestInfo';
    case ValueType.UnitToken:
      return 'UnitToken';
    case ValueType.ContributionState:
      return 'ContributionState';
    case ValueType.ContributionAppearance:
      return 'ContributionAppearance';
    case ValueType.ContributionResult:
      return 'ContributionResult';
    case ValueType.ContributionAppearanceFlags:
      return 'ContributionAppearanceFlags';
    case ValueType.textureAtlas:
      return 'textureAtlas';
    case ValueType.ClassInfo:
      return 'ClassInfo';
    case ValueType.FactionInfo:
      return 'FactionInfo';
    case ValueType.RaceInfo:
      return 'RaceInfo';
    case ValueType.AccountCurrencyTransferResult:
      return 'AccountCurrencyTransferResult';
    case ValueType.BackpackCurrencyInfo:
      return 'BackpackCurrencyInfo';
    case ValueType.CurrencyDisplayInfo:
      return 'CurrencyDisplayInfo';
    case ValueType.CurrencyFilterType:
      return 'CurrencyFilterType';
    case ValueType.CurrencyInfo:
      return 'CurrencyInfo';
    case ValueType.UICursorType:
      return 'UICursorType';
    case ValueType.WorldCursorAnchorType:
      return 'WorldCursorAnchorType';
    case ValueType.SelfResurrectOptionType:
      return 'SelfResurrectOptionType';
    case ValueType.EditModeLayoutInfo:
      return 'EditModeLayoutInfo';
    case ValueType.EditModeLayouts:
      return 'EditModeLayouts';
    case ValueType.EditModeAccountSetting:
      return 'EditModeAccountSetting';
    case ValueType.FramePoint:
      return 'FramePoint';
    case ValueType.EditModeLayoutType:
      return 'EditModeLayoutType';
    case ValueType.EditModeSystem:
      return 'EditModeSystem';
    case ValueType.EditModeAnchorInfo:
      return 'EditModeAnchorInfo';
    case ValueType.JournalLinkTypes:
      return 'JournalLinkTypes';
    case ValueType.EncounterJournalItemInfo:
      return 'EncounterJournalItemInfo';
    case ValueType.EncounterJournalSectionInfo:
      return 'EncounterJournalSectionInfo';
    case ValueType.ItemSlotFilterType:
      return 'ItemSlotFilterType';
    case ValueType.MatchDetails:
      return 'MatchDetails';
    case ValueType.EndOfMatchType:
      return 'EndOfMatchType';
    case ValueType.MatchDetailType:
      return 'MatchDetailType';
    case ValueType.ExpansionDisplayInfo:
      return 'ExpansionDisplayInfo';
    case ValueType.SubscriptionInterstitialResponseType:
      return 'SubscriptionInterstitialResponseType';
    case ValueType.SubscriptionInterstitialType:
      return 'SubscriptionInterstitialType';
    case ValueType.FogOfWarInfo:
      return 'FogOfWarInfo';
    case ValueType.SimpleFont:
      return 'SimpleFont';
    case ValueType.FontScriptInfo:
      return 'FontScriptInfo';
    case ValueType.FontAlphabet:
      return 'FontAlphabet';
    case ValueType.uiFontHeight:
      return 'uiFontHeight';
    case ValueType.TBFFlags:
      return 'TBFFlags';
    case ValueType.colorRGBA:
      return 'colorRGBA';
    case ValueType.FontScriptShadowInfo:
      return 'FontScriptShadowInfo';
    case ValueType.ScriptObject:
      return 'ScriptObject';
    case ValueType.FileAsset:
      return 'FileAsset';
    case ValueType.SingleColorValue:
      return 'SingleColorValue';
    case ValueType.DrawLayer:
      return 'DrawLayer';
    case ValueType.ModelLightType:
      return 'ModelLightType';
    case ValueType.uiRect:
      return 'uiRect';
    case ValueType.vector3:
      return 'vector3';
    case ValueType.AnimationDataEnum:
      return 'AnimationDataEnum';
    case ValueType.ModelBlendOperation:
      return 'ModelBlendOperation';
    case ValueType.TextureAssetDisk:
      return 'TextureAssetDisk';
    case ValueType.uiUnit:
      return 'uiUnit';
    case ValueType.PingTextureType:
      return 'PingTextureType';
    case ValueType.SimpleWindow:
      return 'SimpleWindow';
    case ValueType.FriendInfo:
      return 'FriendInfo';
    case ValueType.WhoInfo:
      return 'WhoInfo';
    case ValueType.EventRealmQueues:
      return 'EventRealmQueues';
    case ValueType.GameEnvironment:
      return 'GameEnvironment';
    case ValueType.ClientPlatformType:
      return 'ClientPlatformType';
    case ValueType.GamePadConfigID:
      return 'GamePadConfigID';
    case ValueType.GamePadConfig:
      return 'GamePadConfig';
    case ValueType.GamePadMappedState:
      return 'GamePadMappedState';
    case ValueType.GamePadRawState:
      return 'GamePadRawState';
    case ValueType.GamePadPowerLevel:
      return 'GamePadPowerLevel';
    case ValueType.GameRule:
      return 'GameRule';
    case ValueType.GossipOptionUIInfo:
      return 'GossipOptionUIInfo';
    case ValueType.FriendshipReputationInfo:
      return 'FriendshipReputationInfo';
    case ValueType.FriendshipReputationRankInfo:
      return 'FriendshipReputationRankInfo';
    case ValueType.GossipPoiInfo:
      return 'GossipPoiInfo';
    case ValueType.GossipOptionRewardType:
      return 'GossipOptionRewardType';
    case ValueType.GossipOptionStatus:
      return 'GossipOptionStatus';
    case ValueType.GossipOptionUIWidgetSetTypes:
      return 'GossipOptionUIWidgetSetTypes';
    case ValueType.ItemCreationContext:
      return 'ItemCreationContext';
    case ValueType.GuildNewsInfo:
      return 'GuildNewsInfo';
    case ValueType.mouseButton:
      return 'mouseButton';
    case ValueType.EmptiableItemLocation:
      return 'EmptiableItemLocation';
    case ValueType.ItemTransmogInfo:
      return 'ItemTransmogInfo';
    case ValueType.LuaValueVariant:
      return 'LuaValueVariant';
    case ValueType.ItemUpgradeItemInfo:
      return 'ItemUpgradeItemInfo';
    case ValueType.ItemUpgradeCostDiscountInfo:
      return 'ItemUpgradeCostDiscountInfo';
    case ValueType.CustomBindingType:
      return 'CustomBindingType';
    case ValueType.BindingSet:
      return 'BindingSet';
    case ValueType.CallbackType:
      return 'CallbackType';
    case ValueType.LFGDungeonInfo:
      return 'LFGDungeonInfo';
    case ValueType.LfgListingCreateData:
      return 'LfgListingCreateData';
    case ValueType.LFGEntryPlaystyle:
      return 'LFGEntryPlaystyle';
    case ValueType.LfgEntryData:
      return 'LfgEntryData';
    case ValueType.GroupFinderActivityInfo:
      return 'GroupFinderActivityInfo';
    case ValueType.AdvancedFilterOptions:
      return 'AdvancedFilterOptions';
    case ValueType.BestDungeonScoreMapInfo:
      return 'BestDungeonScoreMapInfo';
    case ValueType.LfgApplicantData:
      return 'LfgApplicantData';
    case ValueType.PvpRatingInfo:
      return 'PvpRatingInfo';
    case ValueType.LfgCategoryData:
      return 'LfgCategoryData';
    case ValueType.PremadeGroupFinderStyle:
      return 'PremadeGroupFinderStyle';
    case ValueType.LfgSearchResultData:
      return 'LfgSearchResultData';
    case ValueType.LfgSearchResultPlayerInfo:
      return 'LfgSearchResultPlayerInfo';
    case ValueType.WowLocale:
      return 'WowLocale';
    case ValueType.kstringLfgListChat:
      return 'kstringLfgListChat';
    case ValueType.LFGListDisplayType:
      return 'LFGListDisplayType';
    case ValueType.kstringLfgListApplicant:
      return 'kstringLfgListApplicant';
    case ValueType.kstringLfgListSearch:
      return 'kstringLfgListSearch';
    case ValueType.LFGRoles:
      return 'LFGRoles';
    case ValueType.PartyPlaylistEntry:
      return 'PartyPlaylistEntry';
    case ValueType.PlunderstormQueueState:
      return 'PlunderstormQueueState';
    case ValueType.LossOfControlData:
      return 'LossOfControlData';
    case ValueType.UiMapExplorationHitRect:
      return 'UiMapExplorationHitRect';
    case ValueType.MerchantItemInfo:
      return 'MerchantItemInfo';
    case ValueType.MinimapTrackingFilter:
      return 'MinimapTrackingFilter';
    case ValueType.MinimapScriptTrackingFilter:
      return 'MinimapScriptTrackingFilter';
    case ValueType.MinimapScriptTrackingInfo:
      return 'MinimapScriptTrackingInfo';
    case ValueType.TextureAsset:
      return 'TextureAsset';
    case ValueType.MountType:
      return 'MountType';
    case ValueType.MountTypeFlag:
      return 'MountTypeFlag';
    case ValueType.NamePlateFrame:
      return 'NamePlateFrame';
    case ValueType.InspectPVPData:
      return 'InspectPVPData';
    case ValueType.PartyRequestJoinRelation:
      return 'PartyRequestJoinRelation';
    case ValueType.AvgItemLevelCategories:
      return 'AvgItemLevelCategories';
    case ValueType.RestrictPingsTo:
      return 'RestrictPingsTo';
    case ValueType.PartyPoseInfo:
      return 'PartyPoseInfo';
    case ValueType.PartyPoseFlags:
      return 'PartyPoseFlags';
    case ValueType.SimpleFrame:
      return 'SimpleFrame';
    case ValueType.PetJournalPetInfo:
      return 'PetJournalPetInfo';
    case ValueType.PetJournalError:
      return 'PetJournalError';
    case ValueType.PingSubjectType:
      return 'PingSubjectType';
    case ValueType.PingCooldownInfo:
      return 'PingCooldownInfo';
    case ValueType.ScriptRegion:
      return 'ScriptRegion';
    case ValueType.ContextualWorldPingResult:
      return 'ContextualWorldPingResult';
    case ValueType.PingResult:
      return 'PingResult';
    case ValueType.PendingPingOffScreenCallback:
      return 'PendingPingOffScreenCallback';
    case ValueType.PingCooldownStartedCallback:
      return 'PingCooldownStartedCallback';
    case ValueType.PingPinFrameAddedCallback:
      return 'PingPinFrameAddedCallback';
    case ValueType.PingPinFrameRemovedCallback:
      return 'PingPinFrameRemovedCallback';
    case ValueType.PingPinFrameScreenClampStateUpdatedCallback:
      return 'PingPinFrameScreenClampStateUpdatedCallback';
    case ValueType.PingRadialWheelCreatedCallback:
      return 'PingRadialWheelCreatedCallback';
    case ValueType.SendMacroPingCallback:
      return 'SendMacroPingCallback';
    case ValueType.TogglePingListenerCallback:
      return 'TogglePingListenerCallback';
    case ValueType.RelativeContentDifficulty:
      return 'RelativeContentDifficulty';
    case ValueType.MythicPlusRatingSummary:
      return 'MythicPlusRatingSummary';
    case ValueType.PlayerInteractionType:
      return 'PlayerInteractionType';
    case ValueType.PlayerLocation:
      return 'PlayerLocation';
    case ValueType.PvPRanks:
      return 'PvPRanks';
    case ValueType.PvpBrawlInfo:
      return 'PvpBrawlInfo';
    case ValueType.PvPMatchState:
      return 'PvPMatchState';
    case ValueType.RoleShortageReward:
      return 'RoleShortageReward';
    case ValueType.BattlefieldVehicleInfo:
      return 'BattlefieldVehicleInfo';
    case ValueType.BrawlType:
      return 'BrawlType';
    case ValueType.HonorRewardInfo:
      return 'HonorRewardInfo';
    case ValueType.MatchPVPStatColumn:
      return 'MatchPVPStatColumn';
    case ValueType.PVPPersonalRatedInfo:
      return 'PVPPersonalRatedInfo';
    case ValueType.RatedMatchDeserterPenalty:
      return 'RatedMatchDeserterPenalty';
    case ValueType.RatedBGBlitzSpecStats:
      return 'RatedBGBlitzSpecStats';
    case ValueType.RatedSoloShuffleSpecStats:
      return 'RatedSoloShuffleSpecStats';
    case ValueType.PvpTierInfo:
      return 'PvpTierInfo';
    case ValueType.RandomBGInfo:
      return 'RandomBGInfo';
    case ValueType.PVPScoreInfo:
      return 'PVPScoreInfo';
    case ValueType.BattlemasterListInfo:
      return 'BattlemasterListInfo';
    case ValueType.PVPTeamInfo:
      return 'PVPTeamInfo';
    case ValueType.PVPPostMatchCurrencyReward:
      return 'PVPPostMatchCurrencyReward';
    case ValueType.PvpReadyCheckInfo:
      return 'PvpReadyCheckInfo';
    case ValueType.QuestClassification:
      return 'QuestClassification';
    case ValueType.QuestRewardSpellInfo:
      return 'QuestRewardSpellInfo';
    case ValueType.QuestLineInfo:
      return 'QuestLineInfo';
    case ValueType.QuestLineFloorLocation:
      return 'QuestLineFloorLocation';
    case ValueType.QuestWatchType:
      return 'QuestWatchType';
    case ValueType.MapOverlayDisplayLocation:
      return 'MapOverlayDisplayLocation';
    case ValueType.QuestInfo:
      return 'QuestInfo';
    case ValueType.QuestTheme:
      return 'QuestTheme';
    case ValueType.QuestRewardCurrencyInfo:
      return 'QuestRewardCurrencyInfo';
    case ValueType.QuestTagInfo:
      return 'QuestTagInfo';
    case ValueType.QuestFrequency:
      return 'QuestFrequency';
    case ValueType.QuestTag:
      return 'QuestTag';
    case ValueType.WorldQuestQuality:
      return 'WorldQuestQuality';
    case ValueType.QuestObjectiveType:
      return 'QuestObjectiveType';
    case ValueType.QuestRequiredCurrencyInfo:
      return 'QuestRequiredCurrencyInfo';
    case ValueType.QuestSessionCommand:
      return 'QuestSessionCommand';
    case ValueType.QuestSessionPlayerDetails:
      return 'QuestSessionPlayerDetails';
    case ValueType.QuestSessionResult:
      return 'QuestSessionResult';
    case ValueType.RecruitAcceptanceID:
      return 'RecruitAcceptanceID';
    case ValueType.RecruitAFriendRewardsVersion:
      return 'RecruitAFriendRewardsVersion';
    case ValueType.RafInfo:
      return 'RafInfo';
    case ValueType.RafSystemInfo:
      return 'RafSystemInfo';
    case ValueType.RafRecruitActivityState:
      return 'RafRecruitActivityState';
    case ValueType.RafRecruitSubStatus:
      return 'RafRecruitSubStatus';
    case ValueType.RafRewardType:
      return 'RafRewardType';
    case ValueType.RafRecruitmentinfo:
      return 'RafRecruitmentinfo';
    case ValueType.RafPetInfo:
      return 'RafPetInfo';
    case ValueType.RafMountInfo:
      return 'RafMountInfo';
    case ValueType.RafAppearanceInfo:
      return 'RafAppearanceInfo';
    case ValueType.RafTitleInfo:
      return 'RafTitleInfo';
    case ValueType.RafAppearanceSetInfo:
      return 'RafAppearanceSetInfo';
    case ValueType.RafIllusionInfo:
      return 'RafIllusionInfo';
    case ValueType.RafMonthCount:
      return 'RafMonthCount';
    case ValueType.RafReward:
      return 'RafReward';
    case ValueType.ReportType:
      return 'ReportType';
    case ValueType.ReportMajorCategory:
      return 'ReportMajorCategory';
    case ValueType.ReportMinorCategory:
      return 'ReportMinorCategory';
    case ValueType.ReportInfo:
      return 'ReportInfo';
    case ValueType.FactionData:
      return 'FactionData';
    case ValueType.ReputationSortType:
      return 'ReputationSortType';
    case ValueType.ScenarioCriteriaInfo:
      return 'ScenarioCriteriaInfo';
    case ValueType.JailersTowerType:
      return 'JailersTowerType';
    case ValueType.ScenarioInformation:
      return 'ScenarioInformation';
    case ValueType.ScenarioStepInfo:
      return 'ScenarioStepInfo';
    case ValueType.TraitCondInfo:
      return 'TraitCondInfo';
    case ValueType.TraitConfigInfo:
      return 'TraitConfigInfo';
    case ValueType.TraitConfigType:
      return 'TraitConfigType';
    case ValueType.TraitDefinitionInfo:
      return 'TraitDefinitionInfo';
    case ValueType.TraitEntryInfo:
      return 'TraitEntryInfo';
    case ValueType.TraitNodeInfo:
      return 'TraitNodeInfo';
    case ValueType.TraitSubTreeInfo:
      return 'TraitSubTreeInfo';
    case ValueType.TraitTreeInfo:
      return 'TraitTreeInfo';
    case ValueType.TraitNodeInfoPartial:
      return 'TraitNodeInfoPartial';
    case ValueType.TraitDefinitionSubType:
      return 'TraitDefinitionSubType';
    case ValueType.TraitNodeEntryType:
      return 'TraitNodeEntryType';
    case ValueType.TraitEntryRankInfo:
      return 'TraitEntryRankInfo';
    case ValueType.TraitNodeType:
      return 'TraitNodeType';
    case ValueType.CScriptObject:
      return 'CScriptObject';
    case ValueType.luaFunction:
      return 'luaFunction';
    case ValueType.SmoothingType:
      return 'SmoothingType';
    case ValueType.SimpleAnimGroup:
      return 'SimpleAnimGroup';
    case ValueType.SimpleAnim:
      return 'SimpleAnim';
    case ValueType.LoopType:
      return 'LoopType';
    case ValueType.SimpleControlPoint:
      return 'SimpleControlPoint';
    case ValueType.CurveType:
      return 'CurveType';
    case ValueType.SimpleButtonStateToken:
      return 'SimpleButtonStateToken';
    case ValueType.SimpleFontString:
      return 'SimpleFontString';
    case ValueType.BlendMode:
      return 'BlendMode';
    case ValueType.SimplePathAnim:
      return 'SimplePathAnim';
    case ValueType.JustifyHorizontal:
      return 'JustifyHorizontal';
    case ValueType.JustifyVertical:
      return 'JustifyVertical';
    case ValueType.SimpleLine:
      return 'SimpleLine';
    case ValueType.SimpleMaskTexture:
      return 'SimpleMaskTexture';
    case ValueType.FrameStrata:
      return 'FrameStrata';
    case ValueType.HTMLTextType:
      return 'HTMLTextType';
    case ValueType.InsertMode:
      return 'InsertMode';
    case ValueType.ModelLight:
      return 'ModelLight';
    case ValueType.ModelAsset:
      return 'ModelAsset';
    case ValueType.Orientation:
      return 'Orientation';
    case ValueType.StatusBarFillStyle:
      return 'StatusBarFillStyle';
    case ValueType.normalizedValue:
      return 'normalizedValue';
    case ValueType.size:
      return 'size';
    case ValueType.UITextureSliceMode:
      return 'UITextureSliceMode';
    case ValueType.FilterMode:
      return 'FilterMode';
    case ValueType.SocialQueueConfig:
      return 'SocialQueueConfig';
    case ValueType.QueueSpecificInfo:
      return 'QueueSpecificInfo';
    case ValueType.ItemSoundType:
      return 'ItemSoundType';
    case ValueType.Vocalerrorsounds:
      return 'Vocalerrorsounds';
    case ValueType.PvpTalentInfo:
      return 'PvpTalentInfo';
    case ValueType.PvpTalentSlotInfo:
      return 'PvpTalentSlotInfo';
    case ValueType.SpellIdentifier:
      return 'SpellIdentifier';
    case ValueType.DeadlyDebuffInfo:
      return 'DeadlyDebuffInfo';
    case ValueType.SpellChargeInfo:
      return 'SpellChargeInfo';
    case ValueType.SpellCooldownInfo:
      return 'SpellCooldownInfo';
    case ValueType.SpellInfo:
      return 'SpellInfo';
    case ValueType.ScreenLocationType:
      return 'ScreenLocationType';
    case ValueType.SpellBookSpellBank:
      return 'SpellBookSpellBank';
    case ValueType.SpellBookItemInfo:
      return 'SpellBookItemInfo';
    case ValueType.SpellBookItemType:
      return 'SpellBookItemType';
    case ValueType.SpellBookSkillLineInfo:
      return 'SpellBookSkillLineInfo';
    case ValueType.PetInfo:
      return 'PetInfo';
    case ValueType.TtsBoolSetting:
      return 'TtsBoolSetting';
    case ValueType.TtsVoiceType:
      return 'TtsVoiceType';
    case ValueType.FlightPathFaction:
      return 'FlightPathFaction';
    case ValueType.FlightPathState:
      return 'FlightPathState';
    case ValueType.AtlasInfo:
      return 'AtlasInfo';
    case ValueType.TitleIconVersion:
      return 'TitleIconVersion';
    case ValueType.GetTitleIconTextureCallback:
      return 'GetTitleIconTextureCallback';
    case ValueType.UITextureSliceData:
      return 'UITextureSliceData';
    case ValueType.TooltipComparisonItem:
      return 'TooltipComparisonItem';
    case ValueType.TooltipItemComparisonInfo:
      return 'TooltipItemComparisonInfo';
    case ValueType.TooltipComparisonMethod:
      return 'TooltipComparisonMethod';
    case ValueType.TooltipData:
      return 'TooltipData';
    case ValueType.TransmogLocation:
      return 'TransmogLocation';
    case ValueType.WeeklyRewardItemDBID:
      return 'WeeklyRewardItemDBID';
    case ValueType.TransmogCollectionType:
      return 'TransmogCollectionType';
    case ValueType.TransmogPendingInfo:
      return 'TransmogPendingInfo';
    case ValueType.TransmogSearchType:
      return 'TransmogSearchType';
    case ValueType.TransmogPendingType:
      return 'TransmogPendingType';
    case ValueType.TransmogCameraVariation:
      return 'TransmogCameraVariation';
    case ValueType.TransmogAppearanceInfoBySourceData:
      return 'TransmogAppearanceInfoBySourceData';
    case ValueType.TransmogIllusionInfo:
      return 'TransmogIllusionInfo';
    case ValueType.AppearanceSourceInfo:
      return 'AppearanceSourceInfo';
    case ValueType.UIActionType:
      return 'UIActionType';
    case ValueType.EventToastInfo:
      return 'EventToastInfo';
    case ValueType.EventToastDisplayType:
      return 'EventToastDisplayType';
    case ValueType.EventToastEventType:
      return 'EventToastEventType';
    case ValueType.EventToastFlags:
      return 'EventToastFlags';
    case ValueType.GenericWidgetDisplayFrameInfo:
      return 'GenericWidgetDisplayFrameInfo';
    case ValueType.MacroExecuteLineCallback:
      return 'MacroExecuteLineCallback';
    case ValueType.ModelSceneFrame:
      return 'ModelSceneFrame';
    case ValueType.ModelSceneFrameActor:
      return 'ModelSceneFrameActor';
    case ValueType.UIModelSceneActorDisplayInfo:
      return 'UIModelSceneActorDisplayInfo';
    case ValueType.UIModelSceneActorInfo:
      return 'UIModelSceneActorInfo';
    case ValueType.UIModelSceneCameraInfo:
      return 'UIModelSceneCameraInfo';
    case ValueType.ModelSceneType:
      return 'ModelSceneType';
    case ValueType.ModelSceneSetting:
      return 'ModelSceneSetting';
    case ValueType.UIModelSceneActorFlag:
      return 'UIModelSceneActorFlag';
    case ValueType.UISystemType:
      return 'UISystemType';
    case ValueType.TimerCallback:
      return 'TimerCallback';
    case ValueType.TickerCallback:
      return 'TickerCallback';
    case ValueType.BulletTextListWidgetVisualizationInfo:
      return 'BulletTextListWidgetVisualizationInfo';
    case ValueType.CaptureBarWidgetVisualizationInfo:
      return 'CaptureBarWidgetVisualizationInfo';
    case ValueType.CaptureZoneVisualizationInfo:
      return 'CaptureZoneVisualizationInfo';
    case ValueType.DiscreteProgressStepsVisualizationInfo:
      return 'DiscreteProgressStepsVisualizationInfo';
    case ValueType.DoubleIconAndTextWidgetVisualizationInfo:
      return 'DoubleIconAndTextWidgetVisualizationInfo';
    case ValueType.DoubleStateIconRowVisualizationInfo:
      return 'DoubleStateIconRowVisualizationInfo';
    case ValueType.DoubleStatusBarWidgetVisualizationInfo:
      return 'DoubleStatusBarWidgetVisualizationInfo';
    case ValueType.FillUpFramesWidgetVisualizationInfo:
      return 'FillUpFramesWidgetVisualizationInfo';
    case ValueType.HorizontalCurrenciesWidgetVisualizationInfo:
      return 'HorizontalCurrenciesWidgetVisualizationInfo';
    case ValueType.IconAndTextWidgetVisualizationInfo:
      return 'IconAndTextWidgetVisualizationInfo';
    case ValueType.IconTextAndBackgroundWidgetVisualizationInfo:
      return 'IconTextAndBackgroundWidgetVisualizationInfo';
    case ValueType.IconTextAndCurrenciesWidgetVisualizationInfo:
      return 'IconTextAndCurrenciesWidgetVisualizationInfo';
    case ValueType.ItemDisplayVisualizationInfo:
      return 'ItemDisplayVisualizationInfo';
    case ValueType.MapPinAnimationWidgetVisualizationInfo:
      return 'MapPinAnimationWidgetVisualizationInfo';
    case ValueType.ScenarioHeaderCurrenciesAndBackgroundWidgetVisualizationInfo:
      return 'ScenarioHeaderCurrenciesAndBackgroundWidgetVisualizationInfo';
    case ValueType.ScenarioHeaderDelvesWidgetVisualizationInfo:
      return 'ScenarioHeaderDelvesWidgetVisualizationInfo';
    case ValueType.ScenarioHeaderTimerWidgetVisualizationInfo:
      return 'ScenarioHeaderTimerWidgetVisualizationInfo';
    case ValueType.SpacerVisualizationInfo:
      return 'SpacerVisualizationInfo';
    case ValueType.SpellDisplayVisualizationInfo:
      return 'SpellDisplayVisualizationInfo';
    case ValueType.StackedResourceTrackerWidgetVisualizationInfo:
      return 'StackedResourceTrackerWidgetVisualizationInfo';
    case ValueType.StatusBarWidgetVisualizationInfo:
      return 'StatusBarWidgetVisualizationInfo';
    case ValueType.TextColumnRowVisualizationInfo:
      return 'TextColumnRowVisualizationInfo';
    case ValueType.TextWithStateWidgetVisualizationInfo:
      return 'TextWithStateWidgetVisualizationInfo';
    case ValueType.TextWithSubtextWidgetVisualizationInfo:
      return 'TextWithSubtextWidgetVisualizationInfo';
    case ValueType.TextureAndTextRowVisualizationInfo:
      return 'TextureAndTextRowVisualizationInfo';
    case ValueType.TextureAndTextVisualizationInfo:
      return 'TextureAndTextVisualizationInfo';
    case ValueType.TextureWithAnimationVisualizationInfo:
      return 'TextureWithAnimationVisualizationInfo';
    case ValueType.TugOfWarWidgetVisualizationInfo:
      return 'TugOfWarWidgetVisualizationInfo';
    case ValueType.UnitPowerBarWidgetVisualizationInfo:
      return 'UnitPowerBarWidgetVisualizationInfo';
    case ValueType.UIWidgetSetInfo:
      return 'UIWidgetSetInfo';
    case ValueType.ZoneControlVisualizationInfo:
      return 'ZoneControlVisualizationInfo';
    case ValueType.UIWidgetInfo:
      return 'UIWidgetInfo';
    case ValueType.CaptureBarWidgetFillDirectionType:
      return 'CaptureBarWidgetFillDirectionType';
    case ValueType.IconAndTextShiftTextType:
      return 'IconAndTextShiftTextType';
    case ValueType.IconAndTextWidgetState:
      return 'IconAndTextWidgetState';
    case ValueType.IconState:
      return 'IconState';
    case ValueType.ItemDisplayTextDisplayStyle:
      return 'ItemDisplayTextDisplayStyle';
    case ValueType.ItemDisplayTooltipEnabledType:
      return 'ItemDisplayTooltipEnabledType';
    case ValueType.MapPinAnimationType:
      return 'MapPinAnimationType';
    case ValueType.SpellDisplayBorderColor:
      return 'SpellDisplayBorderColor';
    case ValueType.SpellDisplayIconDisplayType:
      return 'SpellDisplayIconDisplayType';
    case ValueType.SpellDisplayTextShownStateType:
      return 'SpellDisplayTextShownStateType';
    case ValueType.SpellDisplayTint:
      return 'SpellDisplayTint';
    case ValueType.StatusBarColorTintValue:
      return 'StatusBarColorTintValue';
    case ValueType.StatusBarOverrideBarTextShownType:
      return 'StatusBarOverrideBarTextShownType';
    case ValueType.StatusBarValueTextType:
      return 'StatusBarValueTextType';
    case ValueType.TugOfWarMarkerArrowShownState:
      return 'TugOfWarMarkerArrowShownState';
    case ValueType.TugOfWarStyleValue:
      return 'TugOfWarStyleValue';
    case ValueType.UIWidgetBlendModeType:
      return 'UIWidgetBlendModeType';
    case ValueType.UIWidgetFlag:
      return 'UIWidgetFlag';
    case ValueType.UIWidgetFontType:
      return 'UIWidgetFontType';
    case ValueType.UIWidgetMotionType:
      return 'UIWidgetMotionType';
    case ValueType.UIWidgetOverrideState:
      return 'UIWidgetOverrideState';
    case ValueType.UIWidgetRewardShownState:
      return 'UIWidgetRewardShownState';
    case ValueType.UIWidgetTextSizeType:
      return 'UIWidgetTextSizeType';
    case ValueType.UIWidgetTextureAndTextSizeType:
      return 'UIWidgetTextureAndTextSizeType';
    case ValueType.UIWidgetTooltipLocation:
      return 'UIWidgetTooltipLocation';
    case ValueType.UIWidgetUpdateAnimType:
      return 'UIWidgetUpdateAnimType';
    case ValueType.WidgetAnimationType:
      return 'WidgetAnimationType';
    case ValueType.WidgetCurrencyClass:
      return 'WidgetCurrencyClass';
    case ValueType.WidgetEnabledState:
      return 'WidgetEnabledState';
    case ValueType.WidgetGlowAnimType:
      return 'WidgetGlowAnimType';
    case ValueType.WidgetIconSizeType:
      return 'WidgetIconSizeType';
    case ValueType.WidgetIconSourceType:
      return 'WidgetIconSourceType';
    case ValueType.WidgetOpacityType:
      return 'WidgetOpacityType';
    case ValueType.WidgetShowGlowState:
      return 'WidgetShowGlowState';
    case ValueType.WidgetShownState:
      return 'WidgetShownState';
    case ValueType.WidgetTextHorizontalAlignmentType:
      return 'WidgetTextHorizontalAlignmentType';
    case ValueType.WidgetUnitPowerBarFlashMomentType:
      return 'WidgetUnitPowerBarFlashMomentType';
    case ValueType.ZoneControlActiveState:
      return 'ZoneControlActiveState';
    case ValueType.ZoneControlDangerFlashType:
      return 'ZoneControlDangerFlashType';
    case ValueType.ZoneControlFillType:
      return 'ZoneControlFillType';
    case ValueType.ZoneControlLeadingEdgeType:
      return 'ZoneControlLeadingEdgeType';
    case ValueType.ZoneControlMode:
      return 'ZoneControlMode';
    case ValueType.ZoneControlState:
      return 'ZoneControlState';
    case ValueType.UIWidgetScale:
      return 'UIWidgetScale';
    case ValueType.UIWidgetLayoutDirection:
      return 'UIWidgetLayoutDirection';
    case ValueType.UIWidgetModelSceneLayer:
      return 'UIWidgetModelSceneLayer';
    case ValueType.ZoneEntry:
      return 'ZoneEntry';
    case ValueType.UIWidgetItemInfo:
      return 'UIWidgetItemInfo';
    case ValueType.UIWidgetRewardInfo:
      return 'UIWidgetRewardInfo';
    case ValueType.UIWidgetSpellInfo:
      return 'UIWidgetSpellInfo';
    case ValueType.UIWidgetHorizontalDirection:
      return 'UIWidgetHorizontalDirection';
    case ValueType.UIWidgetIconInfo:
      return 'UIWidgetIconInfo';
    case ValueType.UIWidgetVisualizationType:
      return 'UIWidgetVisualizationType';
    case ValueType.UIWidgetSetLayoutDirection:
      return 'UIWidgetSetLayoutDirection';
    case ValueType.UnitPowerBarInfo:
      return 'UnitPowerBarInfo';
    case ValueType.CursorStyle:
      return 'CursorStyle';
    case ValueType.PowerType:
      return 'PowerType';
    case ValueType.PhaseReason:
      return 'PhaseReason';
    case ValueType.PvPUnitClassification:
      return 'PvPUnitClassification';
    case ValueType.AddPrivateAuraAnchorArgs:
      return 'AddPrivateAuraAnchorArgs';
    case ValueType.UnitPrivateAuraAppliedSoundInfo:
      return 'UnitPrivateAuraAppliedSoundInfo';
    case ValueType.AuraData:
      return 'AuraData';
    case ValueType.AnchorBinding:
      return 'AnchorBinding';
    case ValueType.UnitAuraUpdateInfo:
      return 'UnitAuraUpdateInfo';
    case ValueType.LFGRole:
      return 'LFGRole';
    case ValueType.GraphicsValidationResult:
      return 'GraphicsValidationResult';
    case ValueType.VignetteInfo:
      return 'VignetteInfo';
    case ValueType.VignetteType:
      return 'VignetteType';
    case ValueType.UIMapPinInfo:
      return 'UIMapPinInfo';
    case ValueType.VignetteObjectiveType:
      return 'VignetteObjectiveType';
    case ValueType.VoiceChatStatusCode:
      return 'VoiceChatStatusCode';
    case ValueType.VoiceChatChannel:
      return 'VoiceChatChannel';
    case ValueType.CommunicationMode:
      return 'CommunicationMode';
    case ValueType.VoiceChannelErrorReason:
      return 'VoiceChannelErrorReason';
    case ValueType.VoiceChatMember:
      return 'VoiceChatMember';
    case ValueType.VoiceTtsDestination:
      return 'VoiceTtsDestination';
    case ValueType.VoiceTtsStatusCode:
      return 'VoiceTtsStatusCode';
    case ValueType.WorldLootObjectInfo:
      return 'WorldLootObjectInfo';
    case ValueType.StartTimerType:
      return 'StartTimerType';
    case ValueType.WoWEntitlementType:
      return 'WoWEntitlementType';
    case ValueType.XMLTemplateInfo:
      return 'XMLTemplateInfo';
    case ValueType.AlliedRaceInfo:
      return 'AlliedRaceInfo';
    case ValueType.AnimaDiversionFrameInfo:
      return 'AnimaDiversionFrameInfo';
    case ValueType.AnimaDiversionNodeState:
      return 'AnimaDiversionNodeState';
    case ValueType.ArdenwealdGardenData:
      return 'ArdenwealdGardenData';
    case ValueType.ArtifactArtInfo:
      return 'ArtifactArtInfo';
    case ValueType.ArtifactTiers:
      return 'ArtifactTiers';
    case ValueType.ArtifactPowerInfo:
      return 'ArtifactPowerInfo';
    case ValueType.ChallengeCompletionInfo:
      return 'ChallengeCompletionInfo';
    case ValueType.ChromieTimeExpansionInfo:
      return 'ChromieTimeExpansionInfo';
    case ValueType.LoadConfigResult:
      return 'LoadConfigResult';
    case ValueType.ClickBindingType:
      return 'ClickBindingType';
    case ValueType.CommentatorHistory:
      return 'CommentatorHistory';
    case ValueType.CommentatorSeries:
      return 'CommentatorSeries';
    case ValueType.CommentatorPlayerData:
      return 'CommentatorPlayerData';
    case ValueType.TrackedSpellCategory:
      return 'TrackedSpellCategory';
    case ValueType.CommentatorUnitData:
      return 'CommentatorUnitData';
    case ValueType.ContentTrackingType:
      return 'ContentTrackingType';
    case ValueType.ContentTrackingResult:
      return 'ContentTrackingResult';
    case ValueType.ContentTrackingTargetType:
      return 'ContentTrackingTargetType';
    case ValueType.EncounterTrackingInfo:
      return 'EncounterTrackingInfo';
    case ValueType.ContentTrackingMapInfo:
      return 'ContentTrackingMapInfo';
    case ValueType.VendorTrackingInfo:
      return 'VendorTrackingInfo';
    case ValueType.ContentTrackingError:
      return 'ContentTrackingError';
    case ValueType.ContentTrackingStopType:
      return 'ContentTrackingStopType';
    case ValueType.CovenantPreviewInfo:
      return 'CovenantPreviewInfo';
    case ValueType.CovenantAbilityType:
      return 'CovenantAbilityType';
    case ValueType.CovenantFeatureInfo:
      return 'CovenantFeatureInfo';
    case ValueType.GarrTalentFeatureSubtype:
      return 'GarrTalentFeatureSubtype';
    case ValueType.CovenantData:
      return 'CovenantData';
    case ValueType.CraftingOrderType:
      return 'CraftingOrderType';
    case ValueType.CraftingOrderDuration:
      return 'CraftingOrderDuration';
    case ValueType.Profession:
      return 'Profession';
    case ValueType.CraftingOrderInfo:
      return 'CraftingOrderInfo';
    case ValueType.CraftingOrderCustomerSearchParams:
      return 'CraftingOrderCustomerSearchParams';
    case ValueType.CraftingOrderCustomerSearchResults:
      return 'CraftingOrderCustomerSearchResults';
    case ValueType.CraftingOrderClaimsRemainingInfo:
      return 'CraftingOrderClaimsRemainingInfo';
    case ValueType.CraftingOrderRequestMyOrdersInfo:
      return 'CraftingOrderRequestMyOrdersInfo';
    case ValueType.NewCraftingOrderInfo:
      return 'NewCraftingOrderInfo';
    case ValueType.CraftingOrderRequestInfo:
      return 'CraftingOrderRequestInfo';
    case ValueType.CraftingOrderResult:
      return 'CraftingOrderResult';
    case ValueType.CraftingOrderSortInfo:
      return 'CraftingOrderSortInfo';
    case ValueType.CraftingOrderRequestCallback:
      return 'CraftingOrderRequestCallback';
    case ValueType.CraftingOrderRequestMyOrdersCallback:
      return 'CraftingOrderRequestMyOrdersCallback';
    case ValueType.TimeEventFlag:
      return 'TimeEventFlag';
    case ValueType.CurioRarity:
      return 'CurioRarity';
    case ValueType.CurioType:
      return 'CurioType';
    case ValueType.CompanionRoleType:
      return 'CompanionRoleType';
    case ValueType.CompanionConfigSlotTypes:
      return 'CompanionConfigSlotTypes';
    case ValueType.ItemWeaponSubclass:
      return 'ItemWeaponSubclass';
    case ValueType.ItemTryOnReason:
      return 'ItemTryOnReason';
    case ValueType.IDOrLink:
      return 'IDOrLink';
    case ValueType.GarrisonFollower:
      return 'GarrisonFollower';
    case ValueType.AutoMissionEnvironmentEffect:
      return 'AutoMissionEnvironmentEffect';
    case ValueType.AutoCombatSpellInfo:
      return 'AutoCombatSpellInfo';
    case ValueType.FollowerAutoCombatStatsInfo:
      return 'FollowerAutoCombatStatsInfo';
    case ValueType.FollowerMissionCompleteInfo:
      return 'FollowerMissionCompleteInfo';
    case ValueType.MissionDeploymentInfo:
      return 'MissionDeploymentInfo';
    case ValueType.MissionEncounterIconInfo:
      return 'MissionEncounterIconInfo';
    case ValueType.GarrisonTalentInfo:
      return 'GarrisonTalentInfo';
    case ValueType.GarrisonTalentTreeInfo:
      return 'GarrisonTalentTreeInfo';
    case ValueType.AutoCombatResult:
      return 'AutoCombatResult';
    case ValueType.GarrisonAbilityInfo:
      return 'GarrisonAbilityInfo';
    case ValueType.NavigationState:
      return 'NavigationState';
    case ValueType.SummonStatus:
      return 'SummonStatus';
    case ValueType.InvasionMapInfo:
      return 'InvasionMapInfo';
    case ValueType.ItemInteractionChargeInfo:
      return 'ItemInteractionChargeInfo';
    case ValueType.ConversionCurrencyCost:
      return 'ConversionCurrencyCost';
    case ValueType.ItemInteractionFrameInfo:
      return 'ItemInteractionFrameInfo';
    case ValueType.UIItemInteractionType:
      return 'UIItemInteractionType';
    case ValueType.RuneforgeLegendaryCraftDescription:
      return 'RuneforgeLegendaryCraftDescription';
    case ValueType.RuneforgeItemPreviewInfo:
      return 'RuneforgeItemPreviewInfo';
    case ValueType.RuneforgeLegendaryComponentInfo:
      return 'RuneforgeLegendaryComponentInfo';
    case ValueType.RuneforgePower:
      return 'RuneforgePower';
    case ValueType.RuneforgePowerFilter:
      return 'RuneforgePowerFilter';
    case ValueType.EncounterLootInfo:
      return 'EncounterLootInfo';
    case ValueType.EncounterLootDropInfo:
      return 'EncounterLootDropInfo';
    case ValueType.EncounterLootDropRollState:
      return 'EncounterLootDropRollState';
    case ValueType.EncounterLootDropRollInfo:
      return 'EncounterLootDropRollInfo';
    case ValueType.CraftingOrderMailInfo:
      return 'CraftingOrderMailInfo';
    case ValueType.MajorFactionData:
      return 'MajorFactionData';
    case ValueType.MajorFactionRenownInfo:
      return 'MajorFactionRenownInfo';
    case ValueType.DBColorExport:
      return 'DBColorExport';
    case ValueType.MapCanvasPosition:
      return 'MapCanvasPosition';
    case ValueType.UIMapType:
      return 'UIMapType';
    case ValueType.UiMapDetails:
      return 'UiMapDetails';
    case ValueType.UiMapPoint:
      return 'UiMapPoint';
    case ValueType.UIMapFlag:
      return 'UIMapFlag';
    case ValueType.MapSeasonBestInfo:
      return 'MapSeasonBestInfo';
    case ValueType.MythicPlusDate:
      return 'MythicPlusDate';
    case ValueType.PerksActivityTags:
      return 'PerksActivityTags';
    case ValueType.PerksActivitiesInfo:
      return 'PerksActivitiesInfo';
    case ValueType.PerksActivitiesPending:
      return 'PerksActivitiesPending';
    case ValueType.PerksActivityInfo:
      return 'PerksActivityInfo';
    case ValueType.PerksActivitiesTracked:
      return 'PerksActivitiesTracked';
    case ValueType.BattlePetOwner:
      return 'BattlePetOwner';
    case ValueType.BattlePetBreedQuality:
      return 'BattlePetBreedQuality';
    case ValueType.PlayerChoiceInfo:
      return 'PlayerChoiceInfo';
    case ValueType.PlayerChoiceRarity:
      return 'PlayerChoiceRarity';
    case ValueType.PlayerChoiceOptionRewardInfo:
      return 'PlayerChoiceOptionRewardInfo';
    case ValueType.PlayerMentorshipStatus:
      return 'PlayerMentorshipStatus';
    case ValueType.SpecializationCurrencyInfo:
      return 'SpecializationCurrencyInfo';
    case ValueType.SpecializationTabInfo:
      return 'SpecializationTabInfo';
    case ValueType.ProfessionsSpecPathState:
      return 'ProfessionsSpecPathState';
    case ValueType.ProfessionsSpecPerkState:
      return 'ProfessionsSpecPerkState';
    case ValueType.ProfessionsSpecTabState:
      return 'ProfessionsSpecTabState';
    case ValueType.ProfTabInfo:
      return 'ProfTabInfo';
    case ValueType.ScriptedAnimationBehavior:
      return 'ScriptedAnimationBehavior';
    case ValueType.ScriptedAnimationFlags:
      return 'ScriptedAnimationFlags';
    case ValueType.ScriptedAnimationTrajectory:
      return 'ScriptedAnimationTrajectory';
    case ValueType.SoulbindConduitType:
      return 'SoulbindConduitType';
    case ValueType.ConduitCollectionData:
      return 'ConduitCollectionData';
    case ValueType.SoulbindNode:
      return 'SoulbindNode';
    case ValueType.SoulbindData:
      return 'SoulbindData';
    case ValueType.SoulbindTree:
      return 'SoulbindTree';
    case ValueType.SoulbindConduitTransactionType:
      return 'SoulbindConduitTransactionType';
    case ValueType.SoulbindConduitData:
      return 'SoulbindConduitData';
    case ValueType.SoulbindModelSceneData:
      return 'SoulbindModelSceneData';
    case ValueType.SoulbindNodeState:
      return 'SoulbindNodeState';
    case ValueType.SplashScreenInfo:
      return 'SplashScreenInfo';
    case ValueType.SplashScreenType:
      return 'SplashScreenType';
    case ValueType.SuperTrackingType:
      return 'SuperTrackingType';
    case ValueType.SuperTrackingMapPinType:
      return 'SuperTrackingMapPinType';
    case ValueType.ProfessionInfo:
      return 'ProfessionInfo';
    case ValueType.CraftingOperationInfo:
      return 'CraftingOperationInfo';
    case ValueType.GatheringOperationInfo:
      return 'GatheringOperationInfo';
    case ValueType.TradeSkillRecipeInfo:
      return 'TradeSkillRecipeInfo';
    case ValueType.CraftingRecipeOutputInfo:
      return 'CraftingRecipeOutputInfo';
    case ValueType.CraftingRecipeSchematic:
      return 'CraftingRecipeSchematic';
    case ValueType.CraftingCurrencyResultData:
      return 'CraftingCurrencyResultData';
    case ValueType.CraftingItemResultData:
      return 'CraftingItemResultData';
    case ValueType.CraftingReagentItemFlag:
      return 'CraftingReagentItemFlag';
    case ValueType.TransmogSetInfo:
      return 'TransmogSetInfo';
    case ValueType.UIFrameType:
      return 'UIFrameType';
    case ValueType.ModifiedInstanceInfo:
      return 'ModifiedInstanceInfo';
    case ValueType.CampaignChapterInfo:
      return 'CampaignChapterInfo';
    case ValueType.CampaignInfo:
      return 'CampaignInfo';
    case ValueType.CampaignFailureReason:
      return 'CampaignFailureReason';
    case ValueType.CampaignState:
      return 'CampaignState';
    case ValueType.WarbandSceneEntry:
      return 'WarbandSceneEntry';
    case ValueType.WarbandSceneSearchInfo:
      return 'WarbandSceneSearchInfo';
    case ValueType.WeeklyRewardChestThresholdType:
      return 'WeeklyRewardChestThresholdType';
    case ValueType.ConquestWeeklyProgress:
      return 'ConquestWeeklyProgress';
    case ValueType.ConquestProgressBarDisplayType:
      return 'ConquestProgressBarDisplayType';
    case ValueType.CachedRewardType:
      return 'CachedRewardType';
    case ValueType.PerksVendorCategoryInfo:
      return 'PerksVendorCategoryInfo';
    case ValueType.PerksVendorItemInfo:
      return 'PerksVendorItemInfo';
    case ValueType.PerksProgramItemDisplayInfo:
      return 'PerksProgramItemDisplayInfo';
    case ValueType.PerksVendorItemUIGroupInfo:
      return 'PerksVendorItemUIGroupInfo';
    case ValueType.AccountData:
      return 'AccountData';
    case ValueType.AccountDataUpdateStatus:
      return 'AccountDataUpdateStatus';
    case ValueType.AccountExportResult:
      return 'AccountExportResult';
    case ValueType.AccountTransType:
      return 'AccountTransType';
    case ValueType.BnetAccountFlag:
      return 'BnetAccountFlag';
    case ValueType.DisableAccountProfilesFlags:
      return 'DisableAccountProfilesFlags';
    case ValueType.ItemCollectionType:
      return 'ItemCollectionType';
    case ValueType.TransmogUseErrorType:
      return 'TransmogUseErrorType';
    case ValueType.ArrowCalloutDirection:
      return 'ArrowCalloutDirection';
    case ValueType.ArrowCalloutType:
      return 'ArrowCalloutType';
    case ValueType.Constants:
      return 'Constants';
    case ValueType.AuctionHouseCommoditySortOrder:
      return 'AuctionHouseCommoditySortOrder';
    case ValueType.AuctionHouseExtraColumn:
      return 'AuctionHouseExtraColumn';
    case ValueType.AuctionHouseFilter:
      return 'AuctionHouseFilter';
    case ValueType.AuctionHouseItemSortOrder:
      return 'AuctionHouseItemSortOrder';
    case ValueType.BagFlag:
      return 'BagFlag';
    case ValueType.BattlePetAbilityFlag:
      return 'BattlePetAbilityFlag';
    case ValueType.BattlePetAbilitySlot:
      return 'BattlePetAbilitySlot';
    case ValueType.BattlePetAbilityTargets:
      return 'BattlePetAbilityTargets';
    case ValueType.BattlePetAbilityTurnFlag:
      return 'BattlePetAbilityTurnFlag';
    case ValueType.BattlePetAbilityTurnType:
      return 'BattlePetAbilityTurnType';
    case ValueType.BattlePetAbilityType:
      return 'BattlePetAbilityType';
    case ValueType.BattlePetAction:
      return 'BattlePetAction';
    case ValueType.BattlePetEffectFlags:
      return 'BattlePetEffectFlags';
    case ValueType.BattlePetEffectParamType:
      return 'BattlePetEffectParamType';
    case ValueType.BattlePetEvent:
      return 'BattlePetEvent';
    case ValueType.BattlePetNpcEmote:
      return 'BattlePetNpcEmote';
    case ValueType.BattlePetNpcTeamFlag:
      return 'BattlePetNpcTeamFlag';
    case ValueType.BattlePetSources:
      return 'BattlePetSources';
    case ValueType.BattlePetSpeciesFlags:
      return 'BattlePetSpeciesFlags';
    case ValueType.BattlePetStateFlag:
      return 'BattlePetStateFlag';
    case ValueType.BattlePetTypes:
      return 'BattlePetTypes';
    case ValueType.BattlePetVisualFlag:
      return 'BattlePetVisualFlag';
    case ValueType.BattlePetVisualRange:
      return 'BattlePetVisualRange';
    case ValueType.BattlepetDbFlags:
      return 'BattlepetDbFlags';
    case ValueType.BattlepetDeletedReason:
      return 'BattlepetDeletedReason';
    case ValueType.BattlepetSlotLockCheat:
      return 'BattlepetSlotLockCheat';
    case ValueType.CalendarCommandType:
      return 'CalendarCommandType';
    case ValueType.CalendarErrorType:
      return 'CalendarErrorType';
    case ValueType.CalendarEventBits:
      return 'CalendarEventBits';
    case ValueType.CalendarFilterFlags:
      return 'CalendarFilterFlags';
    case ValueType.CalendarGetEventType:
      return 'CalendarGetEventType';
    case ValueType.CalendarHolidayFilterType:
      return 'CalendarHolidayFilterType';
    case ValueType.CalendarInviteBits:
      return 'CalendarInviteBits';
    case ValueType.CalendarInviteSortType:
      return 'CalendarInviteSortType';
    case ValueType.CalendarModeratorStatus:
      return 'CalendarModeratorStatus';
    case ValueType.CalendarTexturesType:
      return 'CalendarTexturesType';
    case ValueType.CalendarType:
      return 'CalendarType';
    case ValueType.CalendarWebActionType:
      return 'CalendarWebActionType';
    case ValueType.HolidayCalendarFlags:
      return 'HolidayCalendarFlags';
    case ValueType.HolidayFlags:
      return 'HolidayFlags';
    case ValueType.CharCustomizationType:
      return 'CharCustomizationType';
    case ValueType.ChrCustomizationCategoryFlag:
      return 'ChrCustomizationCategoryFlag';
    case ValueType.ChrCustomizationOptionType:
      return 'ChrCustomizationOptionType';
    case ValueType.WarbandEventState:
      return 'WarbandEventState';
    case ValueType.WarbandGroupFlags:
      return 'WarbandGroupFlags';
    case ValueType.WarbandSceneAnimationEvent:
      return 'WarbandSceneAnimationEvent';
    case ValueType.WarbandSceneAnimationSheatheState:
      return 'WarbandSceneAnimationSheatheState';
    case ValueType.WarbandSceneAnimationStandState:
      return 'WarbandSceneAnimationStandState';
    case ValueType.WarbandScenePlacementType:
      return 'WarbandScenePlacementType';
    case ValueType.ChannelPlayerFlags:
      return 'ChannelPlayerFlags';
    case ValueType.ChatToxityFilterOptOut:
      return 'ChatToxityFilterOptOut';
    case ValueType.ExcludedCensorSources:
      return 'ExcludedCensorSources';
    case ValueType.LanguageFlag:
      return 'LanguageFlag';
    case ValueType.PermanentChatChannelType:
      return 'PermanentChatChannelType';
    case ValueType.ClientSettingsConfigFlag:
      return 'ClientSettingsConfigFlag';
    case ValueType.CurrencyFlags:
      return 'CurrencyFlags';
    case ValueType.CurrencyFlagsB:
      return 'CurrencyFlagsB';
    case ValueType.CurrencyGainFlags:
      return 'CurrencyGainFlags';
    case ValueType.CurrencyTokenCategoryFlags:
      return 'CurrencyTokenCategoryFlags';
    case ValueType.LinkedCurrencyFlags:
      return 'LinkedCurrencyFlags';
    case ValueType.PlayerCurrencyFlags:
      return 'PlayerCurrencyFlags';
    case ValueType.PlayerCurrencyFlagsDbFlags:
      return 'PlayerCurrencyFlagsDbFlags';
    case ValueType.Cursormode:
      return 'Cursormode';
    case ValueType.Causeofdeath:
      return 'Causeofdeath';
    case ValueType.CauseofdeathFlags:
      return 'CauseofdeathFlags';
    case ValueType.Damageclass:
      return 'Damageclass';
    case ValueType.DamageclassType:
      return 'DamageclassType';
    case ValueType.EnvironmentalDamageFlags:
      return 'EnvironmentalDamageFlags';
    case ValueType.Environmentaldamagetype:
      return 'Environmentaldamagetype';
    case ValueType.ActionBarOrientation:
      return 'ActionBarOrientation';
    case ValueType.ActionBarVisibleSetting:
      return 'ActionBarVisibleSetting';
    case ValueType.AuraFrameIconDirection:
      return 'AuraFrameIconDirection';
    case ValueType.AuraFrameIconWrap:
      return 'AuraFrameIconWrap';
    case ValueType.AuraFrameOrientation:
      return 'AuraFrameOrientation';
    case ValueType.BagsDirection:
      return 'BagsDirection';
    case ValueType.BagsOrientation:
      return 'BagsOrientation';
    case ValueType.EditModeActionBarSetting:
      return 'EditModeActionBarSetting';
    case ValueType.EditModeActionBarSystemIndices:
      return 'EditModeActionBarSystemIndices';
    case ValueType.EditModeArchaeologyBarSetting:
      return 'EditModeArchaeologyBarSetting';
    case ValueType.EditModeAuraFrameSetting:
      return 'EditModeAuraFrameSetting';
    case ValueType.EditModeAuraFrameSystemIndices:
      return 'EditModeAuraFrameSystemIndices';
    case ValueType.EditModeBagsSetting:
      return 'EditModeBagsSetting';
    case ValueType.EditModeCastBarSetting:
      return 'EditModeCastBarSetting';
    case ValueType.EditModeChatFrameSetting:
      return 'EditModeChatFrameSetting';
    case ValueType.EditModeDurabilityFrameSetting:
      return 'EditModeDurabilityFrameSetting';
    case ValueType.EditModeMicroMenuSetting:
      return 'EditModeMicroMenuSetting';
    case ValueType.EditModeMinimapSetting:
      return 'EditModeMinimapSetting';
    case ValueType.EditModeObjectiveTrackerSetting:
      return 'EditModeObjectiveTrackerSetting';
    case ValueType.EditModePresetLayouts:
      return 'EditModePresetLayouts';
    case ValueType.EditModeSettingDisplayType:
      return 'EditModeSettingDisplayType';
    case ValueType.EditModeStatusTrackingBarSetting:
      return 'EditModeStatusTrackingBarSetting';
    case ValueType.EditModeStatusTrackingBarSystemIndices:
      return 'EditModeStatusTrackingBarSystemIndices';
    case ValueType.EditModeTimerBarsSetting:
      return 'EditModeTimerBarsSetting';
    case ValueType.EditModeUnitFrameSetting:
      return 'EditModeUnitFrameSetting';
    case ValueType.EditModeUnitFrameSystemIndices:
      return 'EditModeUnitFrameSystemIndices';
    case ValueType.EditModeVehicleSeatIndicatorSetting:
      return 'EditModeVehicleSeatIndicatorSetting';
    case ValueType.MicroMenuOrder:
      return 'MicroMenuOrder';
    case ValueType.MicroMenuOrientation:
      return 'MicroMenuOrientation';
    case ValueType.RaidGroupDisplayType:
      return 'RaidGroupDisplayType';
    case ValueType.SortPlayersBy:
      return 'SortPlayersBy';
    case ValueType.ViewArenaSize:
      return 'ViewArenaSize';
    case ValueType.ViewRaidSize:
      return 'ViewRaidSize';
    case ValueType.JournalEncounterFlags:
      return 'JournalEncounterFlags';
    case ValueType.JournalEncounterIconFlags:
      return 'JournalEncounterIconFlags';
    case ValueType.JournalEncounterItemFlags:
      return 'JournalEncounterItemFlags';
    case ValueType.JournalEncounterLocFlags:
      return 'JournalEncounterLocFlags';
    case ValueType.JournalEncounterSecTypes:
      return 'JournalEncounterSecTypes';
    case ValueType.JournalEncounterSectionFlags:
      return 'JournalEncounterSectionFlags';
    case ValueType.JournalInstanceFlags:
      return 'JournalInstanceFlags';
    case ValueType.ExpansionLandingPageType:
      return 'ExpansionLandingPageType';
    case ValueType.GarrisonFollowerType:
      return 'GarrisonFollowerType';
    case ValueType.GarrisonType:
      return 'GarrisonType';
    case ValueType.GameRuleFlags:
      return 'GameRuleFlags';
    case ValueType.GameRuleType:
      return 'GameRuleType';
    case ValueType.CovenantSkill:
      return 'CovenantSkill';
    case ValueType.CovenantType:
      return 'CovenantType';
    case ValueType.FollowerAbilityCastResult:
      return 'FollowerAbilityCastResult';
    case ValueType.GarrAutoBoardIndex:
      return 'GarrAutoBoardIndex';
    case ValueType.GarrAutoCombatSpellTutorialFlag:
      return 'GarrAutoCombatSpellTutorialFlag';
    case ValueType.GarrAutoCombatTutorial:
      return 'GarrAutoCombatTutorial';
    case ValueType.GarrAutoCombatantRole:
      return 'GarrAutoCombatantRole';
    case ValueType.GarrAutoEventFlags:
      return 'GarrAutoEventFlags';
    case ValueType.GarrAutoMissionEventType:
      return 'GarrAutoMissionEventType';
    case ValueType.GarrAutoPreviewTargetType:
      return 'GarrAutoPreviewTargetType';
    case ValueType.GarrFollowerMissionCompleteState:
      return 'GarrFollowerMissionCompleteState';
    case ValueType.GarrFollowerQuality:
      return 'GarrFollowerQuality';
    case ValueType.GarrTalentCostType:
      return 'GarrTalentCostType';
    case ValueType.GarrTalentFeatureType:
      return 'GarrTalentFeatureType';
    case ValueType.GarrTalentResearchCostSource:
      return 'GarrTalentResearchCostSource';
    case ValueType.GarrTalentSocketType:
      return 'GarrTalentSocketType';
    case ValueType.GarrTalentTreeType:
      return 'GarrTalentTreeType';
    case ValueType.GarrTalentType:
      return 'GarrTalentType';
    case ValueType.GarrTalentUI:
      return 'GarrTalentUI';
    case ValueType.GarrisonTalentAvailability:
      return 'GarrisonTalentAvailability';
    case ValueType.GossipNpcOption:
      return 'GossipNpcOption';
    case ValueType.GossipNpcOptionDisplayFlags:
      return 'GossipNpcOptionDisplayFlags';
    case ValueType.GossipOptionRecFlags:
      return 'GossipOptionRecFlags';
    case ValueType.InputContext:
      return 'InputContext';
    case ValueType.BonusStatIndex:
      return 'BonusStatIndex';
    case ValueType.ItemArmorSubclass:
      return 'ItemArmorSubclass';
    case ValueType.ItemBind:
      return 'ItemBind';
    case ValueType.ItemClass:
      return 'ItemClass';
    case ValueType.ItemConsumableSubclass:
      return 'ItemConsumableSubclass';
    case ValueType.ItemGemColor:
      return 'ItemGemColor';
    case ValueType.ItemMiscellaneousSubclass:
      return 'ItemMiscellaneousSubclass';
    case ValueType.ItemProfessionSubclass:
      return 'ItemProfessionSubclass';
    case ValueType.ItemReagentSubclass:
      return 'ItemReagentSubclass';
    case ValueType.ItemRecipeSubclass:
      return 'ItemRecipeSubclass';
    case ValueType.ItemSocketType:
      return 'ItemSocketType';
    case ValueType.ItemSubclassDisplay:
      return 'ItemSubclassDisplay';
    case ValueType.ItemSubclassFlag:
      return 'ItemSubclassFlag';
    case ValueType.Itemclassfilterflags:
      return 'Itemclassfilterflags';
    case ValueType.Itemsetflags:
      return 'Itemsetflags';
    case ValueType.SlotRegion:
      return 'SlotRegion';
    case ValueType.SlotRegionMask:
      return 'SlotRegionMask';
    case ValueType.SubcontainerType:
      return 'SubcontainerType';
    case ValueType.UIItemInteractionFlags:
      return 'UIItemInteractionFlags';
    case ValueType.LFGListFilter:
      return 'LFGListFilter';
    case ValueType.LogPriority:
      return 'LogPriority';
    case ValueType.LootSlotType:
      return 'LootSlotType';
    case ValueType.UIMapGroupFlag:
      return 'UIMapGroupFlag';
    case ValueType.UIMapSystem:
      return 'UIMapSystem';
    case ValueType.PerksVendorCategoryType:
      return 'PerksVendorCategoryType';
    case ValueType.PetBattleQueueStatus:
      return 'PetBattleQueueStatus';
    case ValueType.PetbattleAuraStateFlags:
      return 'PetbattleAuraStateFlags';
    case ValueType.PetbattleCheatFlags:
      return 'PetbattleCheatFlags';
    case ValueType.PetbattleEffectFlags:
      return 'PetbattleEffectFlags';
    case ValueType.PetbattleEffectType:
      return 'PetbattleEffectType';
    case ValueType.PetbattleEnviros:
      return 'PetbattleEnviros';
    case ValueType.PetbattleInputMoveMsgDebugFlag:
      return 'PetbattleInputMoveMsgDebugFlag';
    case ValueType.PetbattleMoveType:
      return 'PetbattleMoveType';
    case ValueType.PetbattlePboid:
      return 'PetbattlePboid';
    case ValueType.PetbattlePetStatus:
      return 'PetbattlePetStatus';
    case ValueType.PetbattlePlayer:
      return 'PetbattlePlayer';
    case ValueType.PetbattlePlayerInputFlags:
      return 'PetbattlePlayerInputFlags';
    case ValueType.PetbattleResult:
      return 'PetbattleResult';
    case ValueType.PetbattleSlot:
      return 'PetbattleSlot';
    case ValueType.PetbattleSlotAbility:
      return 'PetbattleSlotAbility';
    case ValueType.PetbattleSlotResult:
      return 'PetbattleSlotResult';
    case ValueType.PetbattleState:
      return 'PetbattleState';
    case ValueType.PetbattleTrapstatus:
      return 'PetbattleTrapstatus';
    case ValueType.PetbattleType:
      return 'PetbattleType';
    case ValueType.PetActionFeedback:
      return 'PetActionFeedback';
    case ValueType.PetActionbuttonType:
      return 'PetActionbuttonType';
    case ValueType.PetMode:
      return 'PetMode';
    case ValueType.PetOrders:
      return 'PetOrders';
    case ValueType.PetOverride:
      return 'PetOverride';
    case ValueType.Pettameresult:
      return 'Pettameresult';
    case ValueType.StableResult:
      return 'StableResult';
    case ValueType.UnitMirrorPetFlags:
      return 'UnitMirrorPetFlags';
    case ValueType.PingMode:
      return 'PingMode';
    case ValueType.PingTypeFlags:
      return 'PingTypeFlags';
    case ValueType.CharacterAlternateFormData:
      return 'CharacterAlternateFormData';
    case ValueType.PlayerMentorshipApplicationResult:
      return 'PlayerMentorshipApplicationResult';
    case ValueType.BalanceType:
      return 'BalanceType';
    case ValueType.PowerTypeSign:
      return 'PowerTypeSign';
    case ValueType.PowerTypeSlot:
      return 'PowerTypeSlot';
    case ValueType.CraftingOrderFlags:
      return 'CraftingOrderFlags';
    case ValueType.CraftingOrderItemType:
      return 'CraftingOrderItemType';
    case ValueType.CraftingOrderReagentSource:
      return 'CraftingOrderReagentSource';
    case ValueType.CraftingOrderSortType:
      return 'CraftingOrderSortType';
    case ValueType.CraftingOrderState:
      return 'CraftingOrderState';
    case ValueType.CraftingReagentType:
      return 'CraftingReagentType';
    case ValueType.ItemRecraftFlags:
      return 'ItemRecraftFlags';
    case ValueType.NpcCraftingOrderSetFlags:
      return 'NpcCraftingOrderSetFlags';
    case ValueType.ProfessionActionType:
      return 'ProfessionActionType';
    case ValueType.ProfessionEffect:
      return 'ProfessionEffect';
    case ValueType.ProfessionRating:
      return 'ProfessionRating';
    case ValueType.ProfessionRatingType:
      return 'ProfessionRatingType';
    case ValueType.RcoCloseReason:
      return 'RcoCloseReason';
    case ValueType.SkinningState:
      return 'SkinningState';
    case ValueType.CombinedQuestLogStatus:
      return 'CombinedQuestLogStatus';
    case ValueType.CombinedQuestStatus:
      return 'CombinedQuestStatus';
    case ValueType.QuestCompleteSpellType:
      return 'QuestCompleteSpellType';
    case ValueType.QuestRepeatability:
      return 'QuestRepeatability';
    case ValueType.QuestRewardContextFlags:
      return 'QuestRewardContextFlags';
    case ValueType.QuestTagType:
      return 'QuestTagType';
    case ValueType.QuestTreasurePickerType:
      return 'QuestTreasurePickerType';
    case ValueType.ReportSubComplaintTypes:
      return 'ReportSubComplaintTypes';
    case ValueType.SeasonID:
      return 'SeasonID';
    case ValueType.SocialWhoOrigin:
      return 'SocialWhoOrigin';
    case ValueType.SoftTargetEnableFlags:
      return 'SoftTargetEnableFlags';
    case ValueType.SpellBookSkillLineIndex:
      return 'SpellBookSkillLineIndex';
    case ValueType.TooltipSide:
      return 'TooltipSide';
    case ValueType.TooltipTextureAnchor:
      return 'TooltipTextureAnchor';
    case ValueType.TooltipTextureRelativeRegion:
      return 'TooltipTextureRelativeRegion';
    case ValueType.TooltipDataItemBinding:
      return 'TooltipDataItemBinding';
    case ValueType.TooltipDataLineType:
      return 'TooltipDataLineType';
    case ValueType.TooltipDataType:
      return 'TooltipDataType';
    case ValueType.RecipeRequirementType:
      return 'RecipeRequirementType';
    case ValueType.TradeskillOrderDuration:
      return 'TradeskillOrderDuration';
    case ValueType.TradeskillOrderRecipient:
      return 'TradeskillOrderRecipient';
    case ValueType.TradeskillOrderStatus:
      return 'TradeskillOrderStatus';
    case ValueType.TradeskillRecipeType:
      return 'TradeskillRecipeType';
    case ValueType.TradeskillRelativeDifficulty:
      return 'TradeskillRelativeDifficulty';
    case ValueType.TradeskillSlotDataType:
      return 'TradeskillSlotDataType';
    case ValueType.CraftingReagentSlotInfo:
      return 'CraftingReagentSlotInfo';
    case ValueType.NodeOpFailureReason:
      return 'NodeOpFailureReason';
    case ValueType.SharedStringFlag:
      return 'SharedStringFlag';
    case ValueType.TraitCombatConfigFlags:
      return 'TraitCombatConfigFlags';
    case ValueType.TraitCondFlag:
      return 'TraitCondFlag';
    case ValueType.TraitConditionType:
      return 'TraitConditionType';
    case ValueType.TraitConfigDbState:
      return 'TraitConfigDbState';
    case ValueType.TraitCurrencyFlag:
      return 'TraitCurrencyFlag';
    case ValueType.TraitCurrencyType:
      return 'TraitCurrencyType';
    case ValueType.TraitEdgeType:
      return 'TraitEdgeType';
    case ValueType.TraitEdgeVisualStyle:
      return 'TraitEdgeVisualStyle';
    case ValueType.TraitNodeFlag:
      return 'TraitNodeFlag';
    case ValueType.TraitNodeGroupFlag:
      return 'TraitNodeGroupFlag';
    case ValueType.TraitPointsOperationType:
      return 'TraitPointsOperationType';
    case ValueType.TraitSystemFlag:
      return 'TraitSystemFlag';
    case ValueType.TraitTreeFlag:
      return 'TraitTreeFlag';
    case ValueType.TransmogIllusionFlags:
      return 'TransmogIllusionFlags';
    case ValueType.TransmogModification:
      return 'TransmogModification';
    case ValueType.TransmogSource:
      return 'TransmogSource';
    case ValueType.TransmogType:
      return 'TransmogType';
    case ValueType.UIButtonInfo:
      return 'UIButtonInfo';
    case ValueType.MapIconUIWidgetSetType:
      return 'MapIconUIWidgetSetType';
    case ValueType.UIModelSceneContext:
      return 'UIModelSceneContext';
    case ValueType.UIModelSceneFlags:
      return 'UIModelSceneFlags';
    case ValueType.PrivateAuraIconInfo:
      return 'PrivateAuraIconInfo';
    case ValueType.ScrubStringFlags:
      return 'ScrubStringFlags';
    case ValueType.WarbandSceneFlags:
      return 'WarbandSceneFlags';
    case ValueType.ClickBindingInteraction:
      return 'ClickBindingInteraction';
    case ValueType.CallingStates:
      return 'CallingStates';
    case ValueType.CraftingOrderCustomerCategoryType:
      return 'CraftingOrderCustomerCategoryType';
    case ValueType.CraftingOrderReagentsType:
      return 'CraftingOrderReagentsType';
    case ValueType.CraftingOrderCustomerCategoryFilters:
      return 'CraftingOrderCustomerCategoryFilters';
    case ValueType.CraftingReagentInfo:
      return 'CraftingReagentInfo';
    case ValueType.CurrencyDestroyReason:
      return 'CurrencyDestroyReason';
    case ValueType.CurrencySource:
      return 'CurrencySource';
    case ValueType.GarrisonFollowerAbilityInfo:
      return 'GarrisonFollowerAbilityInfo';
    case ValueType.GarrisonTalentSocketInfo:
      return 'GarrisonTalentSocketInfo';
    case ValueType.ItemGemSubclass:
      return 'ItemGemSubclass';
    case ValueType.ItemRedundancySlot:
      return 'ItemRedundancySlot';
    case ValueType.PointsModifierSourceType:
      return 'PointsModifierSourceType';
    case ValueType.RuneforgePowerState:
      return 'RuneforgePowerState';
    case ValueType.MajorFactionFeatureAbility:
      return 'MajorFactionFeatureAbility';
    case ValueType.MajorFactionType:
      return 'MajorFactionType';
    case ValueType.ProfTraitPerkNodeFlags:
      return 'ProfTraitPerkNodeFlags';
    case ValueType.AddSoulbindConduitReason:
      return 'AddSoulbindConduitReason';
    case ValueType.SoulbindConduitFlags:
      return 'SoulbindConduitFlags';
    case ValueType.SoulbindConduitInstallResult:
      return 'SoulbindConduitInstallResult';

    default:
      // assertNever(type);
      return type;
  }
}
